apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-work-sample-deployment
  labels:
    app.kubernetes.io/name: vmware-work-sample
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vmware-work-sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vmware-work-sample
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: vmware-work-sample
        image: ghcr.io/jtcressy/vmware-work-sample:latest
        args:
        - -bind-addr=:8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
