apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/jtcressy/vmware-work-sample:latest
  newTag: 0.0.0-test2
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: vmware-work-sample-deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/args"
      value:
      - "-test-url=https://google.com"